### ISSUE TITLE
"python2.7 setup.py tests" no longer works

### ISSUE THREAD

**Issue by gson1703** [grrrr/nsgt#12]
Hi,

I tried to verify the fix to issue #2 by running "python2.7 setup.py tests" in a freshly cloned tree (revision 8b573669a9db4fd0428997f34b660dec95a4be62), but it failed with "ImportError: No module named tests".  I think this is because the file tests/__init__.py was removed in commit ac35059884250605edf6f15cd7fed46fc1fdd3fa - was this intentional?

**Comment by grrrr** [comment]
Thank you, that was a mishap. It is back.
