### ISSUE TITLE
Error running ./example/spectrogram.py on fresh install with all dependencies

### ISSUE THREAD

**Issue by kungfujam** [grrrr/nsgt#14]
Just installed. Trying out examples. Error produced as follows.

```
./spectrogram.py '/path/to/sound.wav'
Traceback (most recent call last):
  File "./spectrogram.py", line 84, in <module>
    scl = scale(args.fmin, args.fmax, args.bins, beyond=int(args.reducedform == 2))
TypeError: __init__() got an unexpected keyword argument 'beyond'
```

Proceeds fine when arg removed (creates the log scale object with the default beyond value). However we then hit a warning and then another error:

```
/home/james/anaconda2/envs/nolearn/lib/python2.7/site-packages/nsgt/nsgfwin_sl.py:113: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  g[kk-1][M[kk-1]//2-M[kk]//2:M[kk-1]//2+ceil(M[kk]/2.)] = hannwin(M[kk])
Traceback (most recent call last):
  File "./spectrogram.py", line 102, in <module>
    ncoefs = int(sf.frames*slicq.coef_factor)
AttributeError: NSGT_sliced instance has no attribute 'coef_factor'
```

I see that, whilst NSGT_sliced indeed doesn't have an *attribute* `coef_factor`, it does have a method!

**Comment by grrrr** [comment]
Hi James, i am pretty sure you have an old version of nsgt installed which overshadows the new one.

**Comment by kungfujam** [comment]
Yep! Had done a `sudo python setup.py build`. This uses the wrong python. Your instructions are all correct. Sorry to bother!
