### ISSUE TITLE
Failing test cases

### ISSUE THREAD

**Issue by gson1703** [grrrr/nsgt#2]
Hi, 

When I run "python2.7 setup.py test", a number of test cases report failures. This is from git revision dfbcecad9ad5ccef267fb96ac3d1a84f7c530645 running on Debian 7.

I would attach the full output as a text file, but github won't let me; it says "Attaching documents requires write permission to this repository.  Try again with a PNG, GIF, or JPG.". Here are just a couple of snippets from the output instead:

    test_oct (tests.cq_test.TestNSGT) ... /home/gson/sw/nsgt/nsgt/nsgfwin_sl.py:64: UserWarning: Q-factor too high for frequencies 52.15,53.82,55.54,57.32,59.15,61.05,63.00,65.02,67.10,69.25,71.46,73.75,76.11,78.55,81.06,83.66,86.33,89.10,91.95,94.89,97.93,101.06,104.30,107.64,111.08,114.64,118.31,122.09,126.00,130.03,134.20,138.49,142.92,147.50,152.22,157.09,162.12,167.31,172.67,178.19,183.90,189.78,195.86,202.13,208.60,215.27,222.16,229.27,236.61,244.19,252.00,260.07,268.39,276.98,285.85,295.00,304.44,314.19,324.24,334.62,345.33,356.39,367.79,379.57,391.71,404.25,417.19,430.55,444.33,458.55,473.23
    warn("Q-factor too high for frequencies %s"%",".join("%.2f"%fi for fi in f[q >= qneeded]))

and

    ======================================================================
    FAIL: gtest_oct (tests.slicq_test.TestNSGT_slices)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/gson/sw/nsgt/tests/slicq_test.py", line 53, in gtest_oct
        self.runit(siglen, fmin, fmax, obins, sllen, trlen, real)
      File "/home/gson/sw/nsgt/tests/slicq_test.py", line 18, in runit
        self.assertTrue(close)
    AssertionError: False is not true

**Comment by grrrr** [comment]
Hi, thanks for the report.
This is a error just in the unit tests - should be fixed with commit d9d94adfa3ca9d2d26c1e111fbd7a69243374a1e.
