### ISSUE TITLE
Update nsgt on PyPI

### ISSUE THREAD

**Issue by f0k** [grrrr/nsgt#23]
Would be cool to upload nsgt 0.18 to PyPI. Right now it's still at 0.17, and a `pip3 install nsgt` will give a version that doesn't work in Python 3. (It can of course be circumvented with `pip3 install https://github.com/grrrr/nsgt/archive/0.18.zip`.) Cheers!

**Comment by grrrr** [comment]
Thank you, done!
https://pypi.org/project/nsgt/

**Comment by lostanlen** [comment]
Amazing! many thanks @grrrr

**Comment by f0k** [comment]
Wow, that was fast! :stopwatch: Thanks!
