### ISSUE TITLE
Real-time streamed SliCQ

### ISSUE THREAD

**Issue by lhl2617** [grrrr/nsgt#24]
Hi, thanks for this amazing piece of software and the research!

I'm curious to whether it is possible for sliCQ to be used for streamed, real-time samples (e.g. from a microphone). It would be great if it is (and there is an example). I'm curious about the setup that should be used in a streamed scenario

Thanks in advance!

**Comment by grrrr** [comment]
Hi,
it is absolutely possible to use the module for live streaming.
Have a look at the `transform_stream.py` example and combine that with some live audio input.
Depending on the slice length, there will be latency, and the computational load is also considerable.
best, Thomas

> Am 10.02.2021 um 20:36 schrieb lhl2617 <notifications@github.com>:
> 
> 
> Hi, thanks for this amazing piece of software and the research!
> 
> I'm curious to whether it is possible sliCQ to be used for streamed, real-time samples (e.g. microphone). It would be great if it is (and there is an example). I'm curious as to how to slicing should be done in an online scenario
> 
> Thanks in advance!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Thomas Grill
http://grrrr.org

**Comment by lhl2617** [comment]
Hi Thomas,

Thanks a lot for the reply. I've looked at the example but was misled as it instead just processed a whole file--thanks for clarifying!

I'll try out certain configurations--but I take it there are no experiments done so far with live microphone streamed audio to show some parameters that work well w.r.t. load, latency and other issues? In particular I'm not sure what microphone block length, slice and transition length to use. I'm aiming to minimise latency given octave scale, fmin = 130.8 (C3), fmax = 22050, bins/octave = 12.

Thanks and regards,
Lin

**Comment by grrrr** [comment]
Hi,
latency is directly related to the slice length.
The slice length in turn determines the frequency accuracy of your analysis scale.

For example, with a sample rate=44100, slice length=4096 and f=130.8Hz, 12 integer sine periods will fit into the slice, resulting in an actual frequency of 129.2 Hz
Hence, the slice length depends on your needs for scale accuracy.

best, Thomas

> Am 11.02.2021 um 16:48 schrieb lhl2617 <notifications@github.com>:
> 
> 
> Hi Thomas,
> 
> Thanks a lot for the reply. I've looked at the example but was misled as it instead just processed a whole file--thanks for clarifying!
> 
> I'll try out certain configurations--but I take it there are no experiments done so far with live microphone streamed audio to show some parameters that work well w.r.t. load, latency and other issues? In particular I'm not sure what microphone block length, slice and transition length to use. I'm aiming to minimise latency given octave scale, fmin = 130.8 (C3), fmax = 22050, bins/octave = 12.
> 
> Thanks and regards,
> Lin
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Thomas Grill
http://grrrr.org

**Comment by lhl2617** [comment]
Hi! 

Thanks for the quick reply! 

I'm not sure what the implication of the calculation is--tracing back:
```
(4096/44100) / (1/130.8) = 12.15 
floor(12.15) = 12
(4096/44100) / (1/f) = 12 => f = 129.2 Hz
```
What implication does this number have? I understand that CQT is still subject to the time-freq uncertainty principle and if the slice length is too short, the low frequencies would have poor freq. res..

Further, the paper states that the slices _overlap_--how does this affect real-time slice-wise processing? I assume the transition length is the extent of the overlapping between the windows--if the microphone sends in one slice at a time, should the transition length be 0? or should the microphone send in a block of a few slices and use non-zero transition length (which will cause further issues between blocks I presume).

Thanks again,
Lin

**Comment by sevagh** [comment]
Here's an example I created which seems to work fine: https://github.com/sevagh/Music-Separation-TF/blob/master/algorithms/HPSS_CQNSGT_realtime.py

Much like a "realtime STFT" would involve having a realtime input stream of $hop chunks, say 1024 samples, and ringbuffers of 2*$hop, or window/frame size = 2*$hop, to store the last two hops received from the stream, I adapted the same idea with trlen (transition area length) as the hop and sllen (slice length) as the window/frame size.

**Comment by lhl2617** [comment]
@sevagh Amazing--thanks for this! 

Tangential but this could make it simpler: https://librosa.org/doc/latest/generated/librosa.stream.html
