### ISSUE TITLE
12-96 bins - why stop at 96?

### ISSUE THREAD

**Issue by sevagh** [grrrr/nsgt#26]
The paper uses the values 12, 24, 48, and 96 when describing the CQT-NSGT. What if we go higher? 200 bins per octave? 400? What defines these ranges? Is it related to the piano/keyboard standard octaves?

**Comment by grrrr** [comment]
Hi, you can go as high as you like, but the narrower the frequency grid, the longer the time support of the signal slices will have to be.
Indeed, an octave division of 12 is equivalent to 12-tone equal temperament.

> Am 26.04.2021 um 20:28 schrieb sevagh ***@***.***>:
> 
> 
> The paper uses the values 12, 24, 48, and 96 when describing the CQT-NSGT. What if we go higher? 200 bins per octave? 400? What defines these ranges? Is it related to the piano/keyboard standard octaves?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Thomas Grill
http://grrrr.org

**Comment by sevagh** [comment]
OK. Assuming I can actually use entire songs (aka a signal size of millions of samples @ 48khz) as the input to the NSGT, is there a downside to using giant bin size?

**Comment by sevagh** [comment]
This is actually based on a misunderstanding of the bpo and total bins arguments of different scales. The max bpo in the paper is 192, which corresponds to 2000 frequency bins:
```
>>> import math
>>> bpo = 12
>>> bpo*math.log(22050/20, 2)+1
122.2787552853386
>>> bpo = 96
>>> bpo*math.log(22050/20, 2)+1
971.2300422827088
>>> bpo = 192
>>> bpo*math.log(22050/20, 2)+1
1941.4600845654177
```
So, tl;dr is that "96 bpo" is not a low frequency resolution.
