### ISSUE TITLE
Python3 Support?

### ISSUE THREAD

**Issue by liujimj** [grrrr/nsgt#5]
I haven't tried using NSGT in Python3, but would you be open to pull requests for any necessary changes, if any, to make it Py3 compatible?

**Comment by carlthome** [comment]
Status?

**Comment by smallnamespace** [comment]
@carlthome 
I haven't had a chance to do this yet

**Comment by liujimj** [comment]
@carlthome 

I haven't had a chance to do this yet

**Comment by carlthome** [comment]
Alright, mind if I do a pr?

**Comment by grrrr** [comment]
Great, please go ahead!

**Comment by carlthome** [comment]
https://github.com/grrrr/nsgt/pull/13

**Comment by grrrr** [comment]
Fixed with commit 6ea2240687c85b9633fdf08600feaf381c784c99
